### ISSUE TITLE
.net

### ISSUE THREAD

**Issue by dmitrydvm** [selenide/selenide-ru#4]
Здравствуйте. Selenide на c# не существует случайно?

**Comment by asolntsev** [comment]
@boodoolak есть одна разработка, про неё на днях рассказывали на конференции SeleniymCamp. Но её ещё не зарелизили. Обещали вот-вот выложить на гитхаб. Кстати, они не откажутся от вашей помощи, если что.

**Comment by asolntsev** [comment]
@boodoolak Появилось видео и слайды с этого доклада: http://seleniumcamp.com/talk/using-selenide-on-c-net/

**Comment by dmitrydvm** [comment]
Спасибо!
